# VS Code Development Dockerfile for CRG Overlays
# Base image
FROM ubuntu:latest

# Set the working directory
WORKDIR /workspaces/crg-overlays

# Update OS package list, install packages, and clear apt cache
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y git ssh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Start the bash prompt
CMD ["/bin/bash"]
